from .rojo import build_sourcemap as build_sourcemap, get_rojo_project_path as get_rojo_project_path
from .util import get_module_require as get_module_require, run_bundled_exe as run_bundled_exe

def format(path: str): ...
def get_package_require(package_name: str, package_directory_name: str = ...) -> str: ...
def write_script(build_path: str, content: str, write_as_directory: bool = ..., packages_dir_zip_file_path: str | None = ..., skip_source_map: bool = ..., rojo_project_path: None | str = ...): ...
