from .util import run_bundled_exe as run_bundled_exe

DEFAULT_ROJO_PROJECT_PATH: str
ROJO_SOURCE: str
ROJO_VERSION: str

def get_rojo_project_path(default_path: str | None = ...) -> str: ...
def build_sourcemap(project_json_path: str | None = ...): ...
def get_roblox_path_from_env_path(env_path: str, rojo_project_path: None | str = ...) -> str: ...
