from _typeshed import Incomplete

def get_instance_from_path(path: str) -> str: ...
def run_bundled_exe(exe_name, args: Incomplete | None = ...) -> None: ...
def get_module_require(path: str): ...
def get_header_module(path: str, variable_name: str = ...): ...
