from .rojo import build_sourcemap as build_sourcemap, get_rojo_project_path as get_rojo_project_path
from .tool import get_tool_name as get_tool_name
from .util import run_bundled_exe as run_bundled_exe

WALLY_SOURCE: str
WALLY_VERSION: str
WPT_SOURCE: str
WPT_VERSION: str

def get_wally_name(): ...
def update_wally() -> None: ...
def get_wally_package_nickname(package_wally_path: str) -> str: ...
def require_roblox_wally_package(package_wally_path: str, is_private: bool = ..., is_header: bool = ..., wally_directory_path: str = ...) -> str: ...
