WALLY_SOURCE: str
WALLY_VERSION: str
WPT_SOURCE: str
WPT_VERSION: str

def get_wally_name() -> None: ...
def get_wally_package_types_name() -> None: ...
def update_wally() -> None: ...
def get_wally_package_nickname(package_wally_path: str, prefix: str = ...) -> str: ...
def require_roblox_wally_package(package_wally_path: str, is_private: bool = ..., is_header: bool = ..., wally_directory_path: str = ...) -> str: ...
