from typing import Literal

def set_language_ext(path: str, desired_ext: Literal['luau', 'lua']) -> str: ...
def get_alt_ext_path(path: str) -> str: ...
def update_file_to_ext(path: str, desired_ext: Literal['luau', 'lua']): ...
def get_domain_ext(path: str) -> str | None: ...
def filter_domain(path: str) -> str: ...
def get_if_using_lua_or_luau_ext(path: str) -> str: ...
def get_full_ext(path: str) -> str: ...
def strip_full_ext(path: str) -> str: ...
def get_if_module_script(path: str) -> bool: ...
def insert_domain(build_path: str, domain: str) -> str: ...
def remove_all_path_variants(path: str, domain: str = ...): ...
