def import_type(module_variable_name: str, type_name: str, type_local_name: str = ...) -> str: ...
def indent_block(content: list[str], indent_count: int = ...) -> list[str]: ...
def define_variable(variable_name: str, value: str | None = ..., type_name: str | None = ..., is_private: bool = ..., include_semi_colon: bool = ...): ...
def get_function_header(name: str = ..., parameters: list = ..., return_type: str = ..., is_local: bool = ...) -> str: ...
def get_function_call(name: str = ..., object_name: str = ..., parameters: list = ...) -> str: ...
